#!/usr/bin/env bash

declare -A grid=()

. ./vardump

WALL=$(tput setaf 1)
FREE=$(tput dim)
RST=$(tput sgr0)

print-grid() {
	local x y
	for ((y = 0; y < height; y++)); do
		for ((x = 0; x < width; x++)); do
			local c=${grid[$x,$y]}
			if [[ $c == '#' ]]; then
				c=$WALL'#'$RST
			elif [[ $c == '.' ]]; then
				c=$FREE'.'$RST
			fi
			echo -n "$c"
		done
		echo
	done
}

# read the maze
height=0
while read -r line; do
	width=${#line}
	for ((x = 0; x < width; x++)); do
		key=$x,$height
		c=${line:x:1}

		case "$c" in
			'.') ;;
			'#') ;;
			'S')
				start_loc=$key
				c='.'
				;;
			'E')
				end_loc=$key
				c='.'
				;;
		esac
		grid[$key]=$c
	done

	((height++))
done

echo "maze is $width x $height"
echo "start_loc = $start_loc"
echo "end_loc = $end_loc"

print-grid

# solve the maze
queue=()
queue+=("$start_loc")
distance=0
declare -A visited=()
while ((${#queue[@]} > 0)); do
	# pop off first element from array
	pos=${queue[-1]}
	unset queue[-1]

	printf '%d...\r' "$i"

	IFS=, read -r x y <<< "$pos"
	key=$x,$y

	# check if we are in bounds
	if ((x < 0 || x >= width || y < 0 || y >= height)); then
		continue
	fi

	# check if we have collision
	c=${grid[$key]}
	if [[ $c == '#' ]]; then
		continue
	fi

	# check if we've been here before
	if [[ -n ${visited[$key]} ]]; then
		continue
	fi

	# this move is valid - mark it as seen
	visited[$key]=$distance

	# check if we won
	if [[ $key == $end_loc ]]; then
		echo
		echo solved!
		echo took $distance steps
		break
	fi

	((distance++))

	# queue up trying  all 4 directions
	# north
	nextx=$x
	nexty=$((y - 1))
	queue+=("$nextx,$nexty")

	# south
	nextx=$x
	nexty=$((y + 1))
	queue+=("$nextx,$nexty")

	# east
	nextx=$((x + 1))
	nexty=$y
	queue+=("$nextx,$nexty")

	# west
	nextx=$((x - 1))
	nexty=$y
	queue+=("$nextx,$nexty")
done

print-grid

check-every-shortcut() {
	local radius=20
	local key1=$1

	local startx starty

	echo "checking path at $key1"

	IFS=, read -r startx starty <<< "$key1"

	local y x
	# generate every possible stopping spot
	for ((y = starty - radius; y <= starty + radius; y++)); do
		local ydiff=$((starty - y))
		local ydist=${ydiff#-}
		for ((x = startx - radius + ydist; x <= startx + radius - ydist; x++)); do
			local xdiff=$((startx - x))
			local xdist=${xdiff#-}

			local key2=$x,$y
			local c=${grid[$key2]}
			if [[ $key2 == $key1 ]]; then
				continue
			elif [[ -z $c || $c == '#' ]]; then
				continue
			fi

			# this is a valid move, check it
			local num1=${visited[$key1]}
			local num2=${visited[$key2]}

			[[ -n $num1 && -n $num2 ]] || continue

			local steps=$((xdist + ydist))
			local diff=$((num2 - num1))
			((diff -= steps))
			((diff <= 0)) && continue

			local key="$key1|$key2"

			local existing=${shortcuts[$key]:-0}
			if ((diff > existing)); then
				#echo "(recording (diff=$diff existing=$existing)"
				shortcuts[$key]=$diff
			fi
		done
	done
}

# check every step for possible shortcuts
declare -A shortcuts=()
len=${#visited[@]}
i=0
for key in "${!visited[@]}"; do
	((i++))
	echo "$i/$len"
	check-every-shortcut "$key"
done

vardump shortcuts

declare -A count
total=0
for key in "${!shortcuts[@]}"; do
	value=${shortcuts[$key]}
	if ((value >= 100)); then
		((total++))
		((count[$value]++))
	fi
done
echo "found $total valid shortcuts"

vardump -v count
