#!/usr/bin/env bash

dial=50
accum=0

while read -r line; do
	direction=${line:0:1}
	amount=${line:1}

	echo "$direction $amount (before dial=$dial)"

	case "$direction" in
		L)
			((dial -= amount))
			while ((dial < 0)); do
				((dial += 100))
			done
			;;
		R)
			((dial += amount))
			while ((dial >= 100)); do
				((dial -= 100))
			done
			;;
		*) exit 1;;
	esac

	if ((dial == 0)); then
		((accum++))
	fi
done

echo "number of 0s is $accum"
