#!/usr/bin/env bash

dial=50
accum=0

while read -r line; do
	direction=${line:0:1}
	amount=${line:1}

	echo "$direction $amount (before dial=$dial)"

	compensated=0

	case "$direction" in
		L)
			for ((i = 0; i < amount; i++)); do
				((dial -= 1))
				if ((dial == 0)); then
					echo touched 0
					((accum++))
				fi
				if ((dial < 0)); then
					((dial += 100))
				fi
			done
			;;
		R)
			for ((i = 0; i < amount; i++)); do
				((dial += 1))
				if ((dial >= 100)); then
					((dial -= 100))
				fi
				if ((dial == 0)); then
					echo touched 0
					((accum++))
				fi
			done
			;;
		*) exit 1;;
	esac

#	if ((dial == 0 && compensated == 0)); then
#		echo landed on 0
#		((accum++))
#	fi
done

echo "number of 0s is $accum"
