#!/usr/bin/env bash

. ../../lib/vardump || exit

BEGIN=${1?}
END=${2?}

declare -A map=()

while IFS=: read -r key value; do
	map[$key]=$value
done

total=0

find-path() {
	local name=$1
	local path=$2

	path+="$name,"

	if [[ $name == $END ]]; then
		echo "valid: $path"
		((total++))
		return
	fi

	local connections
	read -ra connections <<< "${map[$name]}"

	for connection in "${connections[@]}"; do
		find-path "$connection" "$path"
	done
}

find-path "$BEGIN" ''

echo "there were $total paths found"
