#!/usr/bin/env bash

evolve() {
	local secret=$1
	local n=$2
	local result i

	for ((i = 0; i < n; i++)); do
		# Calculate the result of multiplying the secret number by 64. Then, mix
		# this result into the secret number. Finally, prune the secret number.
		result=$((secret * 64))
		((secret ^= result))
		((secret %= 16777216))

		# Calculate the result of dividing the secret number by 32. Round the
		# result down to the nearest integer. Then, mix this result into the
		# secret number.  Finally, prune the secret number.
		result=$((secret / 32))
		((secret ^= result))
		((secret %= 16777216))

		# Calculate the result of multiplying the secret number by 2048. Then,
		# mix this result into the secret number. Finally, prune the secret
		# number.
		result=$((secret * 2048))
		((secret ^= result))
		((secret %= 16777216))
	done

	echo "$secret"
}

if ! (return &>/dev/null); then
	evolve "$@"
fi
