#!/usr/bin/env bash

points=()
width=0
height=0
while IFS=, read -r x y; do
	key=$x,$y
	points+=("$key")

	if ((x > width)); then
		width=$x
	fi
	if ((y > height)); then
		height=$y
	fi
done

((width++))
((height++))

#echo "width = $width"
#echo "height = $height"

for ((i = 0; i < ${#points[@]} - 1; i++)); do
	for ((j = i + 1; j < ${#points[@]}; j++)); do
		IFS=, read -r x1 y1 <<< "${points[i]}"
		IFS=, read -r x2 y2 <<< "${points[j]}"

		dx=$((x2 - x1))
		dy=$((y2 - y1))
		dx=${dx#-}
		dy=${dy#-}
		((dx++))
		((dy++))

		area=$((dx * dy))

		echo -e "$area\t$x1 $y1\t$x2 $y2"
	done
done
