#!/usr/bin/env bash

mul_re='mul\(([0-9]{1,3}),([0-9]{1,3})\)$'
do_re='do\(\)$'
dont_re="don't\\(\\)$"

s=$(< /dev/stdin)

s=${s//)/)$'\n'}

accum=0
enabled=true
while read -r line; do
	if [[ $line =~ $do_re ]]; then
		enabled=true
	elif [[ $line =~ $dont_re ]]; then
		enabled=false
	elif [[ $line =~ $mul_re ]] && $enabled; then
		lhs=${BASH_REMATCH[1]}
		rhs=${BASH_REMATCH[2]}
		product=$((lhs * rhs))
		((accum+=product))
	fi
done <<< "$s"

echo "total is $accum"
