#!/usr/bin/env bash

regex='mul\(([0-9]{1,3}),([0-9]{1,3})\)'

s=$(< /dev/stdin)

s=${s//)/)$'\n'}

accum=0
while read -r line; do
	[[ $line =~ $regex ]] || continue

	lhs=${BASH_REMATCH[1]}
	rhs=${BASH_REMATCH[2]}
	product=$((lhs * rhs))
	((accum+=product))
done <<< "$s"

echo "total is $accum"
