#!/usr/bin/env bash

# returns 0 if safe, 1 if unsafe
process-report() {
	local levels=("$@")

	# check first 2 numbers to determine direction
	# we assume each report will have *at least* 2 levels
	local num1=${levels[0]}
	local num2=${levels[1]}

	local ascending
	if ((num1 < num2)); then
		ascending=true
	elif ((num1 > num2)); then
		ascending=false
	else
		return 1
	fi

	local len=${#levels[@]}
	local i
	for ((i = 1; i < len; i++)); do
		local prev=${levels[i - 1]}
		local cur=${levels[i]}

		local diff=$((prev - cur))
		local dist=${diff#-}

		# check distance bounds
		if ((dist < 1 || dist > 3)); then
			return 1
		fi

		if $ascending && ((prev > cur)); then
			# we should be ascending, not descending!
			return 1
		elif ! $ascending && ((prev < cur)); then
			# we should be descending, not ascending!
			return 1
		fi
	done

	return 0
}

numsafe=0
while read -ra levels; do
	if process-report "${levels[@]}"; then
		((numsafe++))
	fi
done

echo "$numsafe safe reports"
