[package]
name = "rust-pt1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
gcd = "2.3.0"
rayon = "1.10.0"
regex = "1.11.1"
