#!/usr/bin/env bash

# turn 'brwrr' into all possibilities

s=${1:-brwrr}
num=$((${#s} - 1))

to-binary() {
	local num=$1
	local b=''
	b+=$((num % 2))

	while ((num >>= 1)); do
		b+=$((num % 2))
	done

	echo "$b"
}
places=$((2 ** num))

for ((i = 0; i < places; i++)); do
	bin=$(to-binary "$i")

	final=''
	for ((j = 0; j < num; j++)); do
		a=${s:j:1}
		b=${bin:j:1}
		b=${b:-0}
		final+=$a$b
	done
	final+=${s:j:1}

	final=${final//0}
	final=${final//1/ }
	echo "$final"
done
