#!/usr/bin/env bash

declare -A map

print-grid() {
	local x y
	for ((y = 0; y < height; y++)); do
		for ((x = 0; x < width; x++)); do
			local c=${map[$x,$y]}
			case "$c" in
				'|') c=$'\e[35m|\e[0m';;
			esac
			echo -n "$c"
		done
		echo
	done
}

# read input
height=0
start=
while read -r line; do
	width=${#line}
	for ((x = 0; x < width; x++)); do
		c=${line:x:1}
		map[$x,$height]=$c

		if [[ $c == 'S' ]]; then
			starting_y=$height
			map[$x,$height]='|'
		fi
	done

	((height++))
done

print-grid

# simulate it line-by-line
numsplits=0
for ((y = starting_y; y < height; y++)); do
	for ((x = 0; x < width; x++)); do
		key=$x,$y
		c=${map[$key]}
		[[ $c == '|' ]] || continue

		# we have a beam now, check 1 below it
		nexty=$((y + 1))
		nextkey=$x,$nexty

		below=${map[$nextkey]}

		case "$below" in
			'.') map[$nextkey]='|';;
			'^')
				((numsplits++))
				# actually split the beam
				lhx=$((x - 1))
				rhx=$((x + 1))

				map[$lhx,$nexty]='|'
				map[$rhx,$nexty]='|'
				;;
			'|') ;;
			*)
				echo "(stopping, got '$below')"
				break 2;;
		esac
	done
done

print-grid
echo "finished - performed $numsplits splits"
